# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_position', models.CharField(max_length=50)),
                ('vacants_amount', models.IntegerField()),
                ('position_type', models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Reemplazo')], default=1)),
                ('working_day_type', models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time')], default=1)),
                ('salary', models.IntegerField()),
                ('comments', models.CharField(max_length=500)),
                ('request_date', models.DateTimeField()),
                ('requested_by', models.CharField(max_length=50)),
                ('requested_for', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('motive', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField()),
                ('requested_by', models.CharField(max_length=50)),
                ('requested_for', models.CharField(max_length=50)),
            ],
        ),
    ]
