# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacant',
            old_name='requested_for',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='requested_for',
            new_name='assigned_to',
        ),
        migrations.AddField(
            model_name='vacant',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacant',
            name='comments',
            field=models.TextField(max_length=500),
        ),
    ]
