# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20151208_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacant',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacant_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacation_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
